config/routes.rb
PostitTemplate::Application.routes.draw do
  
  root to: 'posts#index'

  get '/signup',  to: 'users#new'
  get '/login',   to: 'sessions#new'
  post '/login',  to: 'sessions#create'
  get '/logout',  to: 'sessions#destroy'

  resources :posts, except: :destroy do
    member do
      post 'vote'
    end
    resources :comments, only: :create do
      member do
        post 'vote'
      end
    end
  end
  resources :categories, only: [:create, :new, :show]
  resources :users, only:[:create, :update, :edit, :show]

end

app/models/category.rb
class Category < ActiveRecord::Base

  include Sluggable
  
  has_and_belongs_to_many :posts
  validates :name, presence: true
  validates :name, uniqueness: true

  sluggable_column :name

end

app/models/comment.rb
class Comment < ActiveRecord::Base

  include Voteable
  
  belongs_to :post
  belongs_to :user

  validates :body, presence: true

end

app/models/post.rb
class Post < ActiveRecord::Base

  include Voteable, Sluggable

  belongs_to :creator, foreign_key: :user_id, class_name: "User"
  has_many :comments
  has_and_belongs_to_many :categories

  validates :title, presence: true
  validates :url, presence: true
  validates :description, presence: true
  validates :categories, presence: true

  sluggable_column :title

end

app/models/user.rb
class User < ActiveRecord::Base

  include Sluggable

  has_many :posts
  has_many :comments

  has_secure_password validations: false

  validates :username, presence: true, uniqueness: true
  validates :password, presence: true, on: :create
  validates :password, length: {minimum: 5, :if => :validate_password? }

  def validate_password?
    password.present?
  end

  def admin?
    role == 'admin'
  end

  sluggable_column :username


end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :creator, foreign_key: :user_id, class_name: "User"
  belongs_to :voteable, polymorphic: true

  validates_uniqueness_of :creator, scope: [:voteable_id, :voteable_type]

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?, :admin_log?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def admin_log?
    logged_in? && current_user.admin?
  end

  def login_test
    unless logged_in?
      flash[:error] = "Please log in first."
      redirect_to root_path
    end
  end

  def admin_test
    unless admin_log?
      flash[:error] = "You can't do that."
      redirect_to root_path
    end
  end

  def validate_user
    unless @user == current_user || admin_log?
      flash[:error] = "You can't do that."
      redirect_to root_path
    end
    
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  before_action :admin_test, except: :show
    
  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)

    # binding.pry

    if @category.save
      flash[:notice] = "New category was created."
      redirect_to posts_path
    else
      render :new
    end
  end

  def show
    # binding.pry
    @category = Category.find_by(:slug => params[:id])
    @posts = @category.posts
  end

  private

  def category_params
    params.require(:category).permit([:name])
  end


end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  before_action :login_test

  def create
    @post = Post.find_by(slug: params[:post_id])
    @comment = Comment.new(params.require(:comment).permit(:body))
    @comment.post = @post
    @comment.user = current_user

    if @comment.save
      flash[:notice] = "New comment was created."
      redirect_to post_path(@post)
    else
      render 'posts/show'
    end
  end

  def vote
    @comment = Comment.find(params[:id])
    Vote.create(vote: params[:vote], creator: current_user, voteable: @comment)

    respond_to do |res|
      res.html {redirect_to :back}
      res.js
    end
    
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :set_post, only: [:show, :edit, :update, :vote]
  before_action :login_test, only: [:new, :edit, :update, :create, :vote]
  before_action :validate_user, only: [:edit, :update]

  def index
    @posts = Post.all
  end

  def show
    @comment = Comment.new
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)

    @post.creator = current_user

    if @post.save
      flash[:notice] = "Your post was created."
      redirect_to posts_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @post.update(post_params)
      flash[:notice] = "Your post was updated."
      redirect_to post_path(@post)
    else
      render :edit
    end
  end

  def vote
    vote = Vote.create(vote: params[:vote], creator: current_user, voteable: @post)
    respond_to do |res|
      res.html {redirect_to :back}
      res.js
    end
    
  end

private
  def post_params
    params.require(:post).permit(:title, :url, :description, category_ids: [])
  end

  def set_post
    @post = Post.find_by(:slug => params[:id])
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new

  end

  def create

    @user = User.find_by(username: params[:username])
    # binding.pry
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      flash[:notice] = "You were logged in."
      redirect_to root_path
    else
      flash[:error] = "Something wrong about your user name or password."
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "You were logged out."
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :set_user, only: [:edit, :show, :update]
  before_action :validate_user, only: [:edit, :update]

  def new
    @user = User.new()
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:notice] = "You were registered."
      session[:user_id] = @user.id
      redirect_to root_path
    else
      render :new
    end

  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:notice] = "Your profile was updated"
      redirect_to user_path(@user)
    else
      render :edit
    end

  end

  def show
  end

  private

  def user_params
    params.require(:user).permit([:username, :password, :timezone])
  end

  def set_user
    # binding.pry
    @user = User.find_by(:slug => params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def fix_url(str)
    str.start_with?("http://") ? str : "http://#{str}"
  end

  def format_time(time)
    if logged_in?
      time = time.in_time_zone(current_user.timezone)
    end
    
    time.strftime("%m/%d/%Y %l:%M%P %Z")
  end

  def test_vote?(object)
    !logged_in? || object.votes.find_by(creator: current_user).nil?
  end
end

app/views/categories/_category.html.erb
<span class="badge"><%= link_to category.name, category_path(category) %></span>

app/views/categories/new.html.erb
<%= render 'share/header', content: "Create Categories" %>

<%= render partial: 'share/error', locals: {obj: @category} %>

<div class="well">
  <%= form_for @category do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>
    <br/>
    <%= f.submit class: "btn btn-primary btn-small" %>
  <% end %>
</div>

app/views/categories/show.html.erb
<% all_posts = link_to("All Posts", posts_path) %>
<%= render "share/header", content: "#{all_posts} &raquo; #{@category.name}".html_safe %>

<%= render @posts %>

app/views/comments/_comment.html.erb
<% show_post ||= false %>

<div class="row">
  <div class="well span1 text-center">
    <%= link_to(vote_post_comment_path(comment.post, comment, 'vote' => 'true'), method: 'post', remote: true)  do %>
      <i class="icon-<%= test_vote?(comment) ? 'arrow-up' : 'minus' %> vote_<%= comment.id %>"></i>
    <% end %>
    <br/>
      <span id="comment_<%= comment.id %>_vote"><%= pluralize(comment.total_votes, "vote") %></span>
    <br/>
    <%= link_to(vote_post_comment_path(comment.post, comment, 'vote' => 'false'), method: 'post', remote: true)  do %>
      <i class="icon-<%= test_vote?(comment) ? 'arrow-down' : 'minus' %> vote_<%= comment.id %>"></i>
    <% end %>
  </div>
  <div class="well span8">
    <p>
      "<%= comment.body %>"
      <% if show_post %>
        on <%= link_to comment.post.title, post_path(comment.post) %>
      <% end %>
    </p>
    <p>
      <span class="quiet">by</span> <%= link_to comment.user.username, user_path(comment.user) %>
      <small>at <%= format_time(comment.created_at) %></small>
    </p>
  </div>
</div>

app/views/comments/vote.js.erb
$('.vote_<%= @comment.id %>').attr('class', 'icon-minus vote_<%= @comment.id %>')
$('#comment_<%= @comment.id %>_vote').html("<%= pluralize(@comment.total_votes, "vote") %>")

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<ul class="nav">
  <li>
    <%= link_to "Postit!", root_path, :class => 'brand' %>
  </li>
</ul>

<div class="btn-group nav_item">
  <%= link_to '#', class: "btn btn-tiny dropdown-toggle", 'data-toggle' => 'dropdown' do %>
    Categories <span class='caret'></span>
  <% end %>
  <ul class="dropdown-menu">
    <% Category.all.each do |category| %>
      <li><%= link_to category.name, category_path(category) %></li>
    <% end %>
    <% if admin_log? %>
      <li class="divider"></li>
      <li>
          <%= link_to(new_category_path) do %>
            <i class="icon-plus"></i>
            New Category
          <% end %>
      </li>
    <% end %>
  </ul>
</div>

<% if logged_in? %>
  <div class="nav_item">
    <%= link_to 'New Post', new_post_path, class: "btn btn-success btn-tiny" %>
  </div>
  <div class="btn-group nav_item">
    <%= link_to '#', class: "btn btn-tiny dropdown-toggle", 'data-toggle' => 'dropdown' do %>
    <%= current_user.username %> <span class='caret'></span>
  <% end %>
    <ul class="dropdown-menu">
      <li>
        <%= link_to(edit_user_path(current_user)) do %>
          <i class="icon-pencil"></i>
          edit profile
        <% end %>
      </li>
      <li>
        <%= link_to(user_path(current_user)) do %>
          <i class="icon-user"></i>
          view profile
        <% end %>
      </li>
      <li>
        <%= link_to(logout_path) do %>
          <i class="icon-circle-arrow-left"></i>
          log out
        <% end %>
      </li>
    </ul>
  </div>

<% else %>
  <div class="nav_item">
    <%= link_to 'Sign up', signup_path, class: "btn btn-success btn-tiny" %>
  </div>
  <div class="nav_item">
    <%= link_to 'Log in', login_path, class: "btn btn-tiny" %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tealeaf Academy - Postit</title>
    <meta name="description" content="">
    <meta name="author" content="">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body>
    <header>
      <div class="navbar">
        <div class="navbar-inner">
          <div class="container">
            <%= render 'layouts/navigation' %>
          </div>
        </div>
      </div>
    </header>
    <div id="main" role="main">
      <div class="container">
         <div class="row">
          <div class="span12">
            <%= render 'layouts/messages' %>
            <%= yield %>
          </div>
        </div>
        <footer>
        </footer>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>

app/views/posts/_form.html.erb
<div>
  <%= render partial: "share/error", locals: {obj: @post} %>
</div>

<div class="well">
  <%= form_for @post do |f| %>
  <div class="control-group">
    <%= f.label :title %>
    <%= f.text_field :title %> <br/>
  </div>
  <div class="control-group">
    <%= f.label :url %>
    <%= f.text_field :url %> <br/>
  </div>
  <div class="control-group">
    <%= f.label :description %>
    <%= f.text_area :description, rows: 7 %> <br/>
  </div>
  <div class="control-group inline">
    <%= f.label :categories %>
    <%= f.collection_check_boxes(:category_ids, Category.all, :id, :name) do |cb| %>
      <% cb.label(class: "checkbox inline") { cb.check_box(class: "checkbox") + cb.text } %>
    <% end %>
  </div>
    <%= f.submit class: "btn btn-primary" %>

  <% end %>
</div>

app/views/posts/_post.html.erb
<div class="row">
  <div class="well span1 text-center">
    <%= link_to(vote_post_path(post, 'vote' => 'true'), method: 'post', remote: true)  do %>
      <i class="icon-<%= test_vote?(post) ? 'arrow-up' : 'minus' %> vote_<%= post.to_param %>"></i>
    <% end %>
    <br/>
      <span id="post_<%= post.to_param %>_vote"><%= pluralize(post.total_votes, "vote") %></span>
    <br/>
    <%= link_to(vote_post_path(post, 'vote' => 'false'), method: 'post', remote: true)  do %>
      <i class="icon-<%= test_vote?(post) ? 'arrow-down' : 'minus' %> vote_<%= post.to_param %>"></i>
    <% end %>
  </div>
  <div class="well span8">
    <%= render post.categories %>
    <h4><%= link_to post.title, fix_url(post.url) %></h4>
    <p><%= post.description %></p>
    <p>
      <span class="quiet">Posted by</span> <%= link_to post.creator.username, user_path(post.creator) %>
      <small>at <%= format_time(post.updated_at) %></small> 
    </p>
    <p>
      <small><%= link_to "#{post.comments.size} comments", post_path(post) %></small>
    </p>
  </div>
</div>

app/views/posts/edit.html.erb
<h4 class="lead">Update new post</h4>
<hr>
<%=  render 'form' %>

app/views/posts/index.html.erb
<%= render partial: 'share/header', locals: {content: "All Posts"} %>

<%= render @posts %>

app/views/posts/new.html.erb
<h4 class="lead">Create new post</h4>
<hr>
<%=  render 'form' %>

app/views/posts/show.html.erb
<p>
  <%= render @post.categories %>
  <% if @post.creator == current_user || admin_log? %>
    <span class="pull-right">[<%= link_to "edit this post", edit_post_path(@post) %>]</span>
  <% end %>
</p>


<%= render partial: "share/header", locals: {content: @post.title} %>

<p>
  <%= @post.description %>
  <hr>
</p>

<%= render 'share/error', obj: @comment %>

<% if logged_in? %>
  <%= form_for @comment, url: post_comments_path(@post) do |f| %>
    <%= f.label :body, "Leave a comment" %>
    <%= f.text_area :body, rows: 5 %>
    <br/>
    <%= f.submit class: "btn btn-primary" %>
  <% end %>
<% end %>

<% if @post.comments.any? %>
  <h4>Comments</h4>
<% end %>

<%= render @post.comments %>

app/views/posts/vote.js.erb
$('.vote_<%= @post.to_param %>').attr('class', 'icon-minus vote_<%= @post.to_param %>')
$('#post_<%= @post.to_param %>_vote').html("<%= pluralize(@post.total_votes, "vote") %>")

app/views/share/_error.html.erb
<% unless obj.errors.empty? %>
<div class="row">
  <div class="alert alert-error span8">
    <ul>
      <% obj.errors.full_messages.each do |msg| %>
        <li><p><%= msg %></p></li>
      <% end %>
    </ul>
  </div>
</div>

<% end %>

app/views/share/_header.html.erb
<p class="lead">
  <%= content %>
  <hr>
</p>

app/views/users/_form.html.erb
<%= render 'share/error', obj: @user %>

<div class="well">
  <%= form_for @user do |f| %>
    <div class="control-group">
      <%= f.label :username %>
      <%= f.text_field :username %>
    </div>
    <div class="control-group">
      <%= f.label :password %>
      <%= f.password_field :password %>
    </div>
    <div class="control-group">
      <%= f.label :timezone %>
      <%= f.time_zone_select :timezone, [ActiveSupport::TimeZone['Beijing']] %>
    </div>
    <%= f.submit (@user.new_record? ? "Sign up" : "Update profile"), class: "btn btn-primary" %>
  <% end %>
</div>

app/views/users/edit.html.erb
<%= render 'share/header', content: "Edit Profile" %>

<%= render 'form' %>

app/views/users/new.html.erb
<%= render 'share/header', content: "Register" %>

<%= render 'form' %>

app/views/users/show.html.erb
<%= render 'share/header', content: "Profile: #{@user.username}" %>

<div class="well">
  <dl class="dl-horizontal">
    <dt>Username:</dt>
    <dd><%= @user.username %></dd>
    <dt>Timezone:</dt>
    <dd><%= @user.timezone %></dd>
  </dl>
</div>

<h5><%= "#{@user.username}'s activity" %></h5>
<ul class="nav nav-tabs">
  <li class='<%= 'active' if params[:tab].nil? %>'>
    <%= link_to "Posts (#{@user.posts.size})", user_path(@user) %>
  </li>
  <li class='<%= 'active' if params[:tab] == 'comments' %>'>
    <%= link_to "Comments (#{@user.comments.size})", user_path(@user, tab: "comments") %>
  </li>
</ul>

<% if params[:tab].nil? %>
  <%= render @user.posts %>
<% else %>
  <%= render @user.comments, show_post: true%>
<% end %>